version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - backend
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
      - $PWD/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:

networks:
  backend:
